### ISSUE TITLE
Ubuntu 22.04

### ISSUE THREAD

**Issue by luc122c** [adamrehn/ue4-runtime#11]
NVIDIA have now released CUDA images running on Ubuntu 22.04. It would be great to have pixel streaming base images that use this newer stack. I'm happy to help.
[https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda/tags](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda/tags)

**Comment by adamrehn** [comment]
@luc122c apologies for the extended delay in adding support for Ubuntu 22.04! Back in May 2022, [NVIDIA stopped publishing updates](https://gitlab.com/nvidia/container-images/cudagl/-/commit/80355d13d573dc39b2546a0f60f826711cedb472) to their CUDA + OpenGL "[cudagl](https://hub.docker.com/r/nvidia/cudagl/)" base image, which meant there wasn't an Ubuntu 22.04 version of it available for consumption by downstream projects like ue4-runtime. NVIDIA described this as a "temporary hiatus", so I waited patiently for them to resume publishing new cudagl images. Over a year later, this still hasn't happened.

Today I set about removing Ubuntu 18.04 support from the ue4-runtime codebase, since Canonical ended official support for 18.04 a few months ago, and I've recently received reports from community members that Unreal Engine 5.2 crashes with Vulkan errors when running under Ubuntu 18.04-based containers. When I noticed that the upstream cudagl base image still hadn't been updated, I decided to finally give up on waiting for NVIDIA, and implemented a workaround instead. The build script now [manually builds cudagl images for each version of CUDA](https://github.com/adamrehn/ue4-runtime/blob/1e47ce26364312bbcb0cbcce0065b1512e0eb7a8/build.py#L99-L117), allowing ue4-runtime to support both the latest version of Ubuntu and the latest version of CUDA. This does increase the build time a bit when building images for a lot of different CUDA versions, so I've also switched to [just building images for the newest minor version of each major version of CUDA](https://github.com/adamrehn/ue4-runtime/commit/2513811f9a1a4deb5220bf27c6f9a2f02cfacafe). These changes should help ensure the ue4-runtime codebase is in a position to more rapidly adopt support for new versions of Ubuntu in the future.
