### ISSUE TITLE
Cant find Binaries for Editor anywhere

### ISSUE THREAD

**Issue by Ademord** [adamrehn/ue4-runtime#8]
Hello
I am facing a similar issue as https://github.com/adamrehn/ue4-runtime/issues/5 by @Kingcitaldo125 . I don't seem to find anywhere a Dockerfile, or documentation for that matter, on how to spin up (any) a docker image and just run the UE4 editor (I am using VNC alongside it putting ENV DISPLAY:vnc:blablabla). I am trying to run UE4 on the container but either I cannot find the binaries on the image "adamrehn/ue4-runtime" or I can't find an example on the link you posted at https://github.com/adamrehn/ue4-runtime/issues/5. 

How could I open the UE4 editor?

My compose file atm (planning to mount the project at ~/projects)
```version: '3'
services:
  ndds:
    image: adamrehn/ue4-runtime
    environment:
      - DISPLAY=novnc:0.0
    shm_size: 128gb
    ipc: host
    volumes:
      - "../projects:/home/ue4/projects:rw"    
    depends_on:
      - novnc
    networks:
      - x11
  novnc:  
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH= 2560
      - DISPLAY_HEIGHT= 1440
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
```
And then start up with ```docker run ndds bash``` and manually access the project (or change entrypoint.sh to start the project, once i find the binaries)

**Comment by adamrehn** [comment]
Apologies for the delay in responding to this issue, I've been drowning in work over the past few months and I'm slowly chipping away at my GitHub backlog whenever I get the chance.

The `ue4-runtime` image is designed for running packaged Unreal projects, it does not contain the Unreal Editor, Engine Tools or compiler toolchain. For container images encapsulating the Unreal Editor and Engine Tools see the [ue4-docker](https://github.com/adamrehn/ue4-docker) project. You can find more information about available sources of container images on the [Available Image Sources](https://unrealcontainers.com/docs/obtaining-images/image-sources) page of the Unreal Containers community hub documentation.

Although example code is not currently available for this use case, you can find information about running the Unreal Editor interactively in a container on the [Linux Sandboxed Editor](https://unrealcontainers.com/docs/use-cases/linux-sandboxed-editor) page of the Unreal Containers community hub documentation. If you are planning on using VNC to access the Editor GUI then you can ignore the flags related to bind-mounting the X11 socket from the host system, although you will likely need to add VirtualGL and TurboVNC to your container image to enable GPU acceleration for your VNC session. I have very little experience with this particular configuration myself, but my recommendation would be to use [NVIDIA's VirtualGL + TurboVNC example Dockerfile](https://gitlab.com/nvidia/container-images/samples/-/blob/master/opengl/ubuntu16.04/turbovnc-virtualgl/Dockerfile) as a starting point, extending the the [ue4-minimal](https://docs.adamrehn.com/ue4-docker/building-images/available-container-images#ue4-minimal) or [ue4-full](https://docs.adamrehn.com/ue4-docker/building-images/available-container-images#ue4-full) base image rather than `nvidia/opengl:1.0-glvnd-runtime`.
